# https://taskfile.dev

version: "3"

vars:
  DAY: day-01
  PART: part-1

tasks:
  go:
    dir: "go/{{.DAY}}/{{.PART}}"
    cmds:
      - echo "[Go] Running {{.DAY}}/{{.PART}}..."
      - go run main.go
    silent: true
  go-test:
    dir: "go/{{.DAY}}/{{.PART}}"
    cmds:
      - echo "[Go] Running tests {{.DAY}}/{{.PART}}..."
      - go test
    silent: true
