# https://taskfile.dev

version: "3"

vars:
  LANG: go
  DAY: day-01
  PART: part-1

tasks:
  default:
    dir: "{{.LANG}}/{{.DAY}}/{{.PART}}"
    cmds:
      - echo "Running {{.LANG}}/{{.DAY}}/{{.PART}}..."
      - go run main.go
    silent: true
