# https://taskfile.dev

version: "3"

vars:
  DAY: day-01
  PART: part-1

tasks:
  run:
    dir: "{{.DAY}}/{{.PART}}"
    cmds:
      - echo "Running {{.DAY}}/{{.PART}}..."
      - go run main.go
    silent: true
  test:
    dir: "{{.DAY}}/{{.PART}}"
    cmds:
      - echo "Testing {{.DAY}}/{{.PART}}..."
      - go test {{.CLI_ARGS}}
    silent: true
